### ISSUE TITLE
[Docs] Setting up OpenWRT build system

### ISSUE THREAD

**Issue by arky** [zhaojh329/vwrt#3]
Can you please add instructions for setting up OpenWRT build system in contributors document. I think this will make it easier for new contributors to setup the environment. 
 
Also using a vagrant/docker based environment is also great for developers who are using other operating systems.  

https://github.com/btsimonh/lede-vagrant

**Comment by zhaojh329** [comment]
I will write the document after the basic framework is completed.

**Comment by acimanx** [comment]
@zhaojh329
Please add instructions to make it beginner-friendly 
🙌🙌🙌

**Comment by zhaojh329** [comment]
https://zhaojh329.github.io/oui/

**Comment by acimanx** [comment]
> https://zhaojh329.github.io/oui/
Thanks for your fast reply, but I've read it before.
There are things that I cannot understand. 

For example:
1. Where should I execute 
`echo "src-git oui https://github.com/zhaojh329/oui.git" >> feeds.conf.default`
in my openwrt home directory? Or?

2. I don't have a scripts directory to execute:
`./scripts/feeds update oui`
[url=https://imgbb.com/][img]https://i.ibb.co/M57Lbzk/1.png[/img][/url]

And etc...
