### ISSUE TITLE
[Docs] What is minimum hardware requirements to run VuCi?

### ISSUE THREAD

**Issue by arky** [zhaojh329/vwrt#7]
It is good to document the minimum hardware requirement (RAM 8MB +) of access points that can run VuCI. 

This is will enable people to find suitable devices to flash VuCI as default OpenWRT UI.

**Comment by blinkdr** [comment]
I think, the meaning of vuci is to give a way that the fronted and backend has separated, no matter what the hardware is.

So, you can access OpenWrt router by **/ubus** via http, [example here](https://openwrt.org/docs/techref/ubus).

You can make you own service api just like **vuci-rpc-base** doing.
